server:
  port: ${SERVER_PORT:5450}
spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak-resource}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:5436/auth/realms/my_realm/protocol/openid-connect/certs}